version: "3.8"
services:
    nodeserver:
        build:
            context: app
        command: ["sh", "-c", "dockerize -wait tcp://db:3306 -timeout 30s && npm run migration:run && npm run start:dev "] 
        container_name: app
        ports:
            - "3000:3000"
        networks: 
            - node-network
        volumes: 
            - ./app:/usr/app/
            - /usr/app/node_modules
        depends_on: 
            - db

       
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
    
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
            - ./log:/var/log
            
        environment: 
            - MYSQL_DATABASE=celcito
            - MYSQL_ROOT_PASSWORD=root
        networks: 
           - node-network

networks: 
    node-network:
        driver: bridge

